name: NuGet Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/bayronpo/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}   
          
      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./com.myshoppinglist.models/out/*.nupkg --skip-duplicate --no-symbols true
