name: NuGet Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1
          
      - name: Add nuget source
        run: dotnet nuget add source --username bayronpo --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bayronpo/index.json"
        
      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push **\*.nupkg --skip-duplicate --no-symbols true -s github
