name: NuGet Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write
    name: Update NuGet package
    steps:
          
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build with dotnet
        run: dotnet build --configuration Release
          
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out  

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.2.0            
        
      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/bayronpo/index.json -Username bayronpo -Password ${{ secrets.GITHUB_TOKEN }}
        
      - name: Push generated package to GitHub registry
        run: nuget push **\*.nupkg -Source "GPR" -SkipDuplicate
