name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.myshoppinglist.api/com.myshoppinglist.api.csproj

          # Configuration to build and package
          # BUILD_CONFIGURATION: Release

          # Platform target to compile (default is empty/AnyCPU)
          # BUILD_PLATFORM: x64

          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: com.myshoppinglist.api

          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://nuget.pkg.github.com/bayronpo/index.json

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          # INCLUDE_SYMBOLS: false



# name: NuGet Generation

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: windows-latest
#     permissions:
#       packages: write
#     name: Update NuGet package
#     steps:
#         - name: Publish NuGet
#           uses: brandedoutcast/publish-nuget@v2.5.5
            
#       # - name: Checkout repository
#       #   uses: actions/checkout@v1
          
#       # # - name: Setup .NET Core @ Latest
#       # #   uses: actions/setup-dotnet@v1
#       # #   with:
#       # #     source-url: https://nuget.pkg.github.com/bayronpo/index.json
#       # #   env:
#       # #       NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} 
#       # - name: Add nuget source
#       #   run: dotnet nuget add source --username bayronpo --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bayronpo/index.json"

#       # - name: API Key
#       #   run: nuget setapikey ${{secrets.GITHUB_TOKEN}}  -Source https://nuget.pkg.github.com/bayronpo/index.json
        
#       # - name: Build with dotnet
#       #   run: dotnet build --configuration Release
        
#       # - name: Build solution and generate NuGet package
#       #   run: dotnet pack -c Release -o out

#       # - name: Push generated package to GitHub registry
#       #   run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate -s github
